# Generated by Django 5.2.1 on 2025-06-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="description",
        ),
    ]
