# Generated by Django 5.2.1 on 2025-06-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='task_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
