# Generated by Django 5.2.1 on 2025-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_profile_task_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="completed_task_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
