# Generated by Django 5.2.1 on 2025-06-02 21:09

from datetime import date
import todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_item_deadline_item_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="deadline",
        ),
        migrations.AddField(
            model_name="item",
            name="deadline_date",
            field=models.DateField(default=date.today),
        ),
        migrations.AddField(
            model_name="item",
            name="deadline_time",
            field=models.TimeField(default=todo.models.default_deadline_time),
        ),
    ]
