# Generated by Django 5.2.1 on 2025-06-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0007_alter_item_created_date_alter_item_updated_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="deadline_date",
        ),
    ]
