# Generated by Django 5.2.1 on 2025-06-08 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0010_alter_item_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="deadline_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
