# Generated by Django 5.2.1 on 2025-06-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0011_item_deadline_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="note",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
