# Generated by Django 5.2.1 on 2025-06-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0012_alter_item_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="important",
            field=models.BooleanField(default=False),
        ),
    ]
