# Generated by Django 5.2.1 on 2025-07-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_rename_deadline_date_item_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
