# Generated by Django 5.2.1 on 2025-07-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0015_item_is_expired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="is_expired",
        ),
    ]
