# Generated by Django 5.2.1 on 2025-07-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_profile_completed_task_count"),
        ("todo", "0016_remove_item_is_expired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="remind_me",
        ),
        migrations.AlterField(
            model_name="item",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.profile"
            ),
        ),
    ]
